### ISSUE TITLE
请教楼主个问题。

### ISSUE THREAD

**Issue by wingser** [wangquanfugui233/Bilibili_Python#11]
请教楼主个问题。我下来跑了几天了，哪里能查询到哪些中奖了。好像一直在跑。自己不知道哪中奖了。

**Comment by wangquanfugui233** [comment]
消息找

**Comment by wingser** [comment]
找到了，原来我已经过期了个138的大红包。

**Comment by wangquanfugui233** [comment]
你就离大谱
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月15日 11:47
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [wangquanfugui233/Bilibili_Python] 请教楼主个问题。 (Issue #11)


找到了，原来我已经过期了个138的大红包。

―
